
# Site Settings
title: Terapia Inspire
url: 'https://terapiainspire.com.br/'
logo: "logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Cuido da sua saúde emocional e espiritual Conflitos nos Relacionamentos, Ansiedade, Depressão e Procrastinação
  Sessões on-line ou presencial 
  
instagram: terapia_inspire
social:
  name: terapia_inspire
  links:
    - https://instagram.com/terapia_inspire 

plugins:
  - jekyll-seo-tag

# Tracker
analytics: G-HCHGR8VDSX
adsgoogle: UA-240366032-1
      
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "UTF-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 127.0.0.1
safe: false

